### ISSUE TITLE
我现在完全是以朋友的姿态来挽回你，因为我觉得没有必要闹得这么僵。你别自作多情以为谁都喜欢你，谁喜欢你了，你是万人迷吗？谁对你有期冀了，你想的也太多了吧？对猫猫狗狗有所期冀都比你这个残疾人强得多吧？

### ISSUE THREAD

**Issue by ynl1128** [WinKawaks/WinKawaks.github.io#3]
我不想伤害你，如果你认为伤害你，让你社会性死亡一次无所谓的话请把这条删除。

**Comment by WinKawaks** [comment]
去你妈的以朋友的姿态，怎么有脸说出来这句话的？想死我不拦着，别来恶心我。

**Comment by yanglan1128** [comment]
好好说话别骂人，我真的不喜欢你，你想多了

**Comment by WinKawaks** [comment]
OK，没问题，我想多了。我一点儿也不想跟你这种人做朋友，懂了吗？

**Comment by yanglan1128** [comment]
我大概能猜到你到底是因为什么这么反感，其实我一直不明白，事情过去快十年了，你们两个最后出了问题，而我当时和你几乎见面都不说话吧，我做了什么啊为什么要怪我呢

**Comment by yanglan1128** [comment]
如果不是因为这个心结我实在想不通你为什么反应这么大……

**Comment by WinKawaks** [comment]
完全不懂你在说什么。我之前客客气气给你写一封邮件是想说，最好改变一下你对朋友的态度，否则没人愿意和你做朋友。然后你又完美印证了我说的话。没问题，好自为之吧。

**Comment by yanglan1128** [comment]
不是吧，我完全没看出来是这意思，你不是在说控制欲吗？你不是说不可以题喜欢吗？

**Comment by yanglan1128** [comment]
看得我不知道怎么接，就留言成这样了，你是觉得我对你态度太差了是吗？

**Comment by WinKawaks** [comment]
我来描绘一下你给朋友的感受：完全不懂得尊重别人，不知道相处的边界和底线。

**Comment by yanglan1128** [comment]
狗头保命啊老哥哥，原来我这两年真的变得没有底线而不知了

**Comment by yanglan1128** [comment]
我以为你是能接的住的，就像我当时所处的环境一样，没想到原来你不能……

**Comment by yanglan1128** [comment]
老哥哥对不起＞＜为什么你不早说呀，我自己意识不到……

**Comment by WinKawaks** [comment]
我有非常大的学术压力，请别给我添堵了。我看论文去了。

**Comment by yanglan1128** [comment]
看论文带带我呀，还是不是亲哥了😖

**Comment by yanglan1128** [comment]
我这都半夜一点了……老哥哥不忙的时候能不能投喂几篇论文，求求了

**Comment by yanglan1128** [comment]
老哥哥你要加油啊😴

**Comment by yanglan1128** [comment]
我猜你应该是没看之前其他的留言，这才一个月，一切都才刚刚开始，和换新工作是一样需要适应的，而科研和你之前做的工作又不一样，不是你找个方法学会能用就可以了，需要创新，而且对你所在的平台来说想法要足够好才行，本来就是个慢慢激发灵感的过程，别一上来就这么大压力嘛。我的师兄们都表示自己热爱科研所以才有做下去的动力，可能和导师管的不多、研究方向比较自由有些关系，希望你也能找到自己的热爱吧。哎呀其实我也不知道怎么劝你啦，不知道你能不能稍稍理解一点我当时毕业论文写不出来，天天看医疗纪录片缓解压力的奇葩行为，压力大到骂人也是很好的排解方式，别一个人闷着嘛*⸜( •ᴗ• )⸝*

**Comment by yanglan1128** [comment]
呃……打扰了，有件事忘问了，小孟听说你出国留学了，想问问你那只收北邮的学生吗，吉大通信专业的申请有希望嘛，需要提前准备什么，他之前加过你，但应该是因为我的问题你没理他吧……

**Comment by yanglan1128** [comment]
等下个月今天考完试之后我可能会被听医生劝不能再郁闷下去吧，不然真的麻烦了，哦这该死的体检报告终于发了，建议治疗是啥意思，吃药还是动刀啊@_@……

**Comment by yanglan1128** [comment]
我在北京没找到你之后去了广州顺德和厦门，时隔四年之后终于去看海了，我太喜欢厦门的海和这一路的美食了，吃到了从台湾回来就一直惦记的姜母鸭，佛跳墙吃的有点不习惯，在日光岩看日落，顶着大太阳和大仙人掌合影，如果不是太热真的可以考虑定居，这大概是我今年唯一开心的一段时间吧，但是心情还是受了点影响没怎么拍照
![IMG_20201002_171046](https://user-images.githubusercontent.com/45323762/98198730-9d3ad000-1f64-11eb-9fbb-191b3e3bdb39.jpg)
![IMG_20201002_121930](https://user-images.githubusercontent.com/45323762/98198743-a461de00-1f64-11eb-8811-d5dd9d9fa492.jpg)

**Comment by yanglan1128** [comment]
围观转岗人员面试，内部竞聘竞争好激烈，一不小心就只能去门店卖卡😱年末两个月时间要在写2020年总结2021年计划中度过，可是才三天就词穷了……改了20天的视频能不能让我收尾了，还有不到一个月的时间就要考试，可是什么都记不住，明天的我还能更惨嘛……今天老哥哥会发论文嘛，不知道

**Comment by yanglan1128** [comment]
为什么老哥哥不愿说出研究方向呢？

**Comment by yanglan1128** [comment]
听歌倒是蛮积极的，丝毫看不出时差和学术压力

**Comment by yanglan1128** [comment]
---原始邮件---
发件人: "Qu Zhiyu"<notifications@github.com&gt;
发送时间: 2020年11月4日 00:55:15
收件人: "WinKawaks/WinKawaks.github.io"<WinKawaks.github.io@noreply.github.com&gt;;
抄送: "yanglan1128"<1214864520@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [WinKawaks/WinKawaks.github.io] 我现在完全是以朋友的姿态来挽回你，因为我觉得没有必要闹得这么僵。你别自作多情以为谁都喜欢你，谁喜欢你了，你是万人迷吗？谁对你有期冀了，你想的也太多了吧？对猫猫狗狗有所期冀都比你这个残疾人强得多吧？ (#3)




 
我有非常大的学术压力，请别给我添堵了。我看论文去了。

**Comment by yanglan1128** [comment]
说我全平台人肉，你不也是一样嘛，必须到别的平台留言才能体现出关系非凡

**Comment by yanglan1128** [comment]
学术大佬名义上看论文实际上看卖唱够不够社会性死亡，好像不够啊，这条还不能删

**Comment by ynl1128** [comment]
一天的时间，你考虑一下，24小时之后我就去说了


 
---原始邮件---
发件人: "杨斓"<yanglanyl28@qq.com&gt;
发送时间: 2020年11月11日 00:23:37
收件人: "WinKawaks/WinKawaks.github.io"<reply@reply.github.com&gt;;"zhiyu_qu"<zhiyu_qu@qq.com&gt;;"WinKawaks/Personal-Applications"<reply@reply.github.com&gt;;"Author"<author@noreply.github.com&gt;;"WinKawaks/WinKawaks.github.io"<winkawaks.github.io@noreply.github.com&gt;;
主题: 巧了，小姐姐和前任的现任同名，我更要帮你撮合了你看我是在哪说比较合适，私聊还是公开评论能让你看到的那种？😳
