### ISSUE TITLE
曲智宇，你留下一句我不尊重你一走了之，好，我努力从你的阴影中走出来，剩下的关系仅限探讨学术嘛，可是你双标啊，和找你探讨学术的人说别添堵了，对卖唱感兴趣是吧？行，还做什么学术，街头艺人不香吗？

### ISSUE THREAD

**Issue by ynl1128** [WinKawaks/WinKawaks.github.io#4]

**Comment by WinKawaks** [comment]
你大早上发什么疯呢过来一顿冷嘲热讽？是在展示实力吗大侦探？我有什么义务跟你讨论学术吗？

**Comment by yanglan1128** [comment]
哦，不是零时差吗？竟然不是了？大早上？对我来说现在才是大早上，刚才发消息的时间才还没睡着呢谢谢。谁是大侦探，你认识就不许我认识了？

**Comment by yanglan1128** [comment]
我没有资格和科学家(街头艺人)讨论学术问题ಠ_ಠ

**Comment by yanglan1128** [comment]
我能感受到你喜欢卖唱小姐姐，甚至用你朋友的话来说频繁的点赞评论有点倒贴的意思，从没见你这么活跃过，可是为啥不留在上海呢，前任现任都在不是很好～

**Comment by yanglan1128** [comment]
小姐姐知道你喜欢她嘛？如果不知道我帮你告诉她啊⌯'ㅅ'⌯
