### ISSUE TITLE
我开个问题列表想想我最近的疑惑都有什么啊，你有时间看着能解答的帮忙答一下，答完我应该就不会再来留言了

### ISSUE THREAD

**Issue by ghost** [WinKawaks/WinKawaks.github.io#43]
首先是我们还能做朋友吗，这条我先替你答，不能了。虽然我觉得我还能凑合，我多没底线啊

**Comment by yl1128** [comment]
第二个是，你是怎么想的骗了cxy约等于骗了我说你还在北京，是因为我不想告诉他还是想先出成绩再说，这事你还打算和人家解释吗，还是说你不打算和他做朋友了？

**Comment by yl1128** [comment]
第三个，我猜的，你喜欢小姐姐是真的吗

**Comment by yl1128** [comment]
从假设我喜欢是真的的角度讲，你不能接受我什么，还是说谁都一样都不能接受

**Comment by yl1128** [comment]
从不喜欢的角度出发，我需要做什么你才能不恨我，不那么暴躁的骂人，必须消失嘛

**Comment by yl1128** [comment]
我的电话都是机器人接的吗？

**Comment by yl1128** [comment]
求你的研究方向

**Comment by yl1128** [comment]
如果你去年去的是泰国现在是不是就不会这样了，你后悔吗？

**Comment by yl1128** [comment]
你还会回来吗？还是留在那再也不回来了

**Comment by yl1128** [comment]
你是不是当年也以这么决绝的态度对待过那谁呀？我开始盲猜你俩到最后的时刻出了问题，不然她后来也没必要公开秀恩爱伤害你吧。你现在后悔吗？

**Comment by yl1128** [comment]
如果人人说你是渣男，你要为自己辩解什么吗

**Comment by yl1128** [comment]
为什么cxy回忆他前女友说那次见我们觉得我们应该可以？听得我都迷茫了，我们那个时候是什么状态啊，为什么会给人那种暧昧的错觉，那时候不是互相嫌弃对方的工作不好吗😒

**Comment by yl1128** [comment]
挺可笑的，别人觉得我们是那样的可是我们只记得吃饭谁没付钱
