### ISSUE TITLE
贴一个对你的真实评价吧

### ISSUE THREAD

**Issue by ynl1128** [WinKawaks/WinKawaks.github.io#7]
![Screenshot_20201108_135009](https://user-images.githubusercontent.com/45323762/98458224-644f6500-21c9-11eb-8232-3416927ad4b0.png)

**Comment by yanglan1128** [comment]
舔狗今天舔到小姐姐了嘛？థ౪థ

**Comment by yanglan1128** [comment]
其实我还有好多事情没弄明白你就走了，比如说去年到底是泰国的朋友鸽了你还是你个鸽了他(出现了不同的说法)；你还记得我问过你送彩墨给谁吧，那明明是老相识为什么误导我是个男性朋友；还有你屏蔽cxy到底是出于什么心理，也不想和他做朋友了吗；你明明有喜欢的小姐姐身边又不乏追求者，又何必之前来试探我喜欢过谁，还不告诉我你的真实想法；我不想用上面一个贱字来总结你的所作所为，这样不客观，对你不公平。
